In [60]:
import pandas as pd
import geopandas as gpd
import matplotlib.pyplot as plt

In [61]:
final = pd.read_csv('/Users/sahana_krishnaraj/Github/siting-optimizer-lmichallange/true_final.csv')
county = gpd.read_file('/Users/sahana_krishnaraj/Github/siting-optimizer-lmichallange/tl_2025_us_county/tl_2025_us_county.shp')
state = gpd.read_file('/Users/sahana_krishnaraj/Github/siting-optimizer-lmichallange/tl_2025_us_state/tl_2025_us_state.shp')


'''
things we want:
low wfh, low drought, high wind plan, high gas and oil production?

things imma do:
fill the gas, oil, wind nas with 0s
County X dominates county Y if X is at least as good in all objectives and strictly better in at least one. dominating means out competes
'''

In [62]:
final.head()
final
#county.head()

,GEOID,Latitude,Longitude,geometry,Gas Production Quantity,Oil Production Quantity,Wind Plant Capacity,Wildfire Hazard Potential Score,Drought Risk Score,County,State,State Name,Pareto Efficient
0,15001,18.978000,-155.688000,POINT (-155.688 18.978),0.000000,0.000000,0.334645,0.117,0.106041,Hawaii County,HI,Hawaii,False
1,15009,20.800100,-156.539000,POINT (-156.539 20.8001),0.000000,0.000000,0.334645,0.100,0.181957,Maui County,HI,Hawaii,False
2,15003,21.669200,-157.950100,POINT (-157.9501 21.6692),0.000000,0.000000,0.371260,0.197,0.044702,Honolulu County,HI,Hawaii,False
3,15003,21.680400,-157.982000,POINT (-157.982 21.6804),0.000000,0.000000,0.382505,0.197,0.044702,Honolulu County,HI,Hawaii,False
4,48061,26.118900,-97.343100,POINT (-97.3431 26.1189),0.000000,0.000000,0.540691,0.103,0.000000,Cameron County,TX,Texas,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1190,2185,70.169433,-146.316676,POINT (-146.3166757 70.16943313),0.674542,0.000000,0.000000,0.151,0.100000,North Slope Borough,AK,Alaska,False
1191,2185,70.309122,-148.670664,POINT (-148.6706638 70.30912164),0.000000,0.955906,0.000000,0.151,0.100000,North Slope Borough,AK,Alaska,False
1192,2185,70.324819,-149.945492,POINT (-149.9454917 70.32481918),0.000000,0.772550,0.000000,0.151,0.100000,North Slope Borough,AK,Alaska,False
1193,2185,70.331718,-147.879900,POINT (-147.8799 70.33171813),0.764759,0.000000,0.000000,0.151,0.100000,North Slope Borough,AK,Alaska,False
1194,2185,70.474762,-149.525500,POINT (-149.5255 70.47476248),0.000000,0.562962,0.000000,0.151,0.100000,North Slope Borough,AK,Alaska,False

In [75]:
#final["Pareto Efficient"] = True
final.shape
(final["Pareto Efficient"] == True).sum()

np.int64(1195)

In [76]:
countstate = pd.merge(county, state[["STATEFP","STUSPS","NAME"]], on="STATEFP", how="left")
countstate.rename(columns={"geometry": "cn geometry"}, inplace=True)
countstate.head()

,STATEFP,COUNTYFP,COUNTYNS,GEOID,GEOIDFQ,NAME_x,NAMELSAD,LSAD,CLASSFP,MTFCC,...,CBSAFP,METDIVFP,FUNCSTAT,ALAND,AWATER,INTPTLAT,INTPTLON,cn geometry,STUSPS,NAME_y
0,40,075,01101825,40075,0500000US40075,Kiowa,Kiowa County,06,H1,G4020,...,None,None,A,2629039892,40296743,+34.9214893,-098.9816168,"POLYGON ((-98.95506 35.11643, -98.94903 35.116...",OK,Oklahoma
1,46,079,01265776,46079,0500000US46079,Lake,Lake County,06,H1,G4020,...,None,None,A,1457916151,31746795,+44.0284497,-097.1232229,"POLYGON ((-96.88886 43.9353, -96.88886 43.9351...",SD,South Dakota
2,37,033,01008542,37033,0500000US37033,Caswell,Caswell County,06,H1,G4020,...,None,None,A,1102042927,8293623,+36.3943252,-079.3396193,"POLYGON ((-79.14343 36.4422, -79.14345 36.4418...",NC,North Carolina
3,48,377,01383974,48377,0500000US48377,Presidio,Presidio County,06,H1,G4020,...,None,None,A,9985057447,1773188,+30.0058912,-104.2616192,"POLYGON ((-104.98078 30.62552, -104.98073 30.6...",TX,Texas
4,39,057,01074041,39057,0500000US39057,Greene,Greene County,06,H1,G4020,...,19430,None,A,1071302625,6798109,+39.6874785,-083.8948943,"POLYGON ((-84.10668 39.68891, -84.10662 39.689...",OH,Ohio

In [77]:
final['GEOID'] = final['GEOID'].astype(str)
final["GEOIDlen"] = final['GEOID'].str.len()
final["GEOIDlen"].value_counts()
final['GEOID'] = final['GEOID'].str.zfill(5)
final = final.drop(columns=['GEOIDlen'])
final['GEOID'] = final['GEOID'].astype('int64')

In [78]:
final.GEOID.dtype
countstate['GEOID'] = countstate['GEOID'].astype(str)
countstate['GEOIDlen'] = countstate['GEOID'].str.len()
countstate = countstate.drop(columns=['GEOIDlen'])
countstate['GEOID'] = countstate['GEOID'].astype('int64')

In [79]:
#merge final and countstate
merged = pd.merge(final, countstate[["NAMELSAD","STUSPS","NAME_y","GEOID", "cn geometry"]], on="GEOID", how="left")
merged.head()
merged.drop(columns=["NAMELSAD", "STUSPS","NAME_y"], inplace=True)

In [80]:
#merged.drop(merged[merged["STUSPS"].isna()].index, inplace=True)
# = merged.drop()
#merged = merged.drop(columns=['State', 'County'])
#merged.rename(columns={"STUSPS": "State", "County": "State Name","NAMELSAD":"County"}, inplace=True)
merged

,GEOID,Latitude,Longitude,geometry,Gas Production Quantity,Oil Production Quantity,Wind Plant Capacity,Wildfire Hazard Potential Score,Drought Risk Score,County,State,State Name,Pareto Efficient,cn geometry
0,15001,18.978000,-155.688000,POINT (-155.688 18.978),0.000000,0.000000,0.334645,0.117,0.106041,Hawaii County,HI,Hawaii,True,"POLYGON ((-155.03 19.7921, -155.02991 19.79207..."
1,15009,20.800100,-156.539000,POINT (-156.539 20.8001),0.000000,0.000000,0.334645,0.100,0.181957,Maui County,HI,Hawaii,True,"MULTIPOLYGON (((-157.36626 21.11666, -157.3634..."
2,15003,21.669200,-157.950100,POINT (-157.9501 21.6692),0.000000,0.000000,0.371260,0.197,0.044702,Honolulu County,HI,Hawaii,True,"MULTIPOLYGON (((-178.44359 28.41899, -178.4383..."
3,15003,21.680400,-157.982000,POINT (-157.982 21.6804),0.000000,0.000000,0.382505,0.197,0.044702,Honolulu County,HI,Hawaii,True,"MULTIPOLYGON (((-178.44359 28.41899, -178.4383..."
4,48061,26.118900,-97.343100,POINT (-97.3431 26.1189),0.000000,0.000000,0.540691,0.103,0.000000,Cameron County,TX,Texas,True,"POLYGON ((-97.34064 25.92886, -97.34081 25.928..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1190,2185,70.169433,-146.316676,POINT (-146.3166757 70.16943313),0.674542,0.000000,0.000000,0.151,0.100000,North Slope Borough,AK,Alaska,True,"POLYGON ((-166.97174 68.3452, -166.97157 68.35..."
1191,2185,70.309122,-148.670664,POINT (-148.6706638 70.30912164),0.000000,0.955906,0.000000,0.151,0.100000,North Slope Borough,AK,Alaska,True,"POLYGON ((-166.97174 68.3452, -166.97157 68.35..."
1192,2185,70.324819,-149.945492,POINT (-149.9454917 70.32481918),0.000000,0.772550,0.000000,0.151,0.100000,North Slope Borough,AK,Alaska,True,"POLYGON ((-166.97174 68.3452, -166.97157 68.35..."
1193,2185,70.331718,-147.879900,POINT (-147.8799 70.33171813),0.764759,0.000000,0.000000,0.151,0.100000,North Slope Borough,AK,Alaska,True,"POLYGON ((-166.97174 68.3452, -166.97157 68.35..."
1194,2185,70.474762,-149.525500,POINT (-149.5255 70.47476248),0.000000,0.562962,0.000000,0.151,0.100000,North Slope Borough,AK,Alaska,True,"POLYGON ((-166.97174 68.3452, -166.97157 68.35..."

In [ ]:
"""# For production columns: NA = 0 (no production = no resource)
merged['Wind Plant Capacity'] = merged['Wind Plant Capacity'].fillna(0)
merged['Oil Production Quantity'] = merged['Oil Production Quantity'].fillna(0)
merged['Gas Production Quantity'] = merged['Gas Production Quantity'].fillna(0)

# For risk columns: NA = median (unknown risk = average risk)
merged['Wildfire Hazard Potential Score'] = merged['Wildfire Hazard Potential Score'].fillna(merged['Wildfire Hazard Potential Score'].median())
merged['Drought Risk Score'] = merged['Drought Risk Score'].fillna(merged['Drought Risk Score'].median())
merged.columns.values[11] = "State Name" 
"""

In [81]:
merged.head()

,GEOID,Latitude,Longitude,geometry,Gas Production Quantity,Oil Production Quantity,Wind Plant Capacity,Wildfire Hazard Potential Score,Drought Risk Score,County,State,State Name,Pareto Efficient,cn geometry
0,15001,18.9780,-155.6880,POINT (-155.688 18.978),0.0,0.0,0.334645,0.117,0.106041,Hawaii County,HI,Hawaii,True,"POLYGON ((-155.03 19.7921, -155.02991 19.79207..."
1,15009,20.8001,-156.5390,POINT (-156.539 20.8001),0.0,0.0,0.334645,0.100,0.181957,Maui County,HI,Hawaii,True,"MULTIPOLYGON (((-157.36626 21.11666, -157.3634..."
2,15003,21.6692,-157.9501,POINT (-157.9501 21.6692),0.0,0.0,0.371260,0.197,0.044702,Honolulu County,HI,Hawaii,True,"MULTIPOLYGON (((-178.44359 28.41899, -178.4383..."
3,15003,21.6804,-157.9820,POINT (-157.982 21.6804),0.0,0.0,0.382505,0.197,0.044702,Honolulu County,HI,Hawaii,True,"MULTIPOLYGON (((-178.44359 28.41899, -178.4383..."
4,48061,26.1189,-97.3431,POINT (-97.3431 26.1189),0.0,0.0,0.540691,0.103,0.000000,Cameron County,TX,Texas,True,"POLYGON ((-97.34064 25.92886, -97.34081 25.928..."

In [ ]:
merged = merged.groupby('GEOID', as_index=False).agg({
    'County': 'first',
    'State': 'first',
    'State Name': 'first',
    'Wildfire Hazard Potential Score': 'mean',
    'Drought Risk Score': 'mean',
    'Wind Plant Capacity': 'sum',  # Total capacity across all plants
    'Oil Production Quantity': 'sum',  # Total production
    'Gas Production Quantity': 'sum',
    'Latitude': 'first',
    'Longitude': 'first',
    'geometry': 'first',  # Keep the geometry for mapping
    'Pareto Efficient': 'first',
    'cn geometry': 'first'
})

In [84]:
merged.shape

(494, 14)

In [85]:
minimize = ["Wildfire Hazard Potential Score", "Drought Risk Score"]
maximize = ["Wind Plant Capacity", "Oil Production Quantity", "Gas Production Quantity"]
for i in range(len(merged)):
    for j in range(len(merged)): #nested loop to comare within 
        if i == j:
            continue #skip the same row comparison -- redundant
        # check if row j is better than row i
        #all() function returns true if all elements in the iterable are true

        #the alls ensure that for a row to dominate another row, it has to be better in all the minimize and maximize columns
        all_min = all(merged.iloc[j][minimize] <= merged.iloc[i][minimize]) #checks each column in current row and compares it with the column in the previous row (dominates if they are lower than previous good!)
        all_max = all(merged.iloc[j][maximize] >= merged.iloc[i][maximize]) #checks each column in current row and compares it with the column in the previous row (dominates if they are higher than previous good!)
        
        #the anys ensure that for a row to dominate another row, it has to be strictly better in at least one of the minimize or maximize columns (like an edge case for when two rows have same values but how do u see if its better)
        any_strict = any(merged.iloc[j][minimize] < merged.iloc[i][minimize]) or \
            any(merged.iloc[j][maximize] > merged.iloc[i][maximize])

        #finally check if all conditions are met
        if all_min and all_max and any_strict:
            merged.iloc[i, merged.columns.get_loc("Pareto Efficient")] = False
            break #no need to check further, move to next row

In [87]:
merged["Pareto Efficient"].value_counts()

Pareto Efficient
False    456
True      38
Name: count, dtype: int64

In [88]:
merged.to_csv("true_final.csv", index=False)

In [3]:
import pandas as pd 
final_csv = pd.read_csv("true_final.csv")

In [ ]:
final_csv.columns
final_csv[final_csv["Pareto Efficient"] == True]


# Check for duplicates (should be 0)
print(f"Duplicates remaining: {df_final['GEOID'].duplicated().sum()}")

,GEOID,Latitude,Longitude,geometry,Gas Production Quantity,Oil Production Quantity,Wind Plant Capacity,Wildfire Hazard Potential Score,Drought Risk Score,County,State,State Name,Pareto Efficient
37,48409,28.173800,-97.811000,POINT (-97.811 28.1738),0.000000,0.000000,0.702991,0.089,0.069270,San Patricio County,TX,Texas,True
77,22075,29.074842,-89.169747,POINT (-89.16974745 29.07484204),0.000000,0.048224,0.000000,0.031,0.306344,Plaquemines Parish,LA,Louisiana,True
86,22075,29.246292,-89.409263,POINT (-89.409263 29.24629198),0.072693,0.000000,0.000000,0.031,0.306344,Plaquemines Parish,LA,Louisiana,True
91,22057,29.393469,-90.295929,POINT (-90.29592936 29.39346926),0.297075,0.047296,0.000000,0.095,0.461868,Lafourche Parish,LA,Louisiana,True
102,22101,29.604216,-91.529606,POINT (-91.52960632 29.60421631),0.142723,0.032555,0.000000,0.072,0.276310,St. Mary Parish,LA,Louisiana,True
105,22101,29.719414,-91.490812,POINT (-91.49081195 29.71941387),0.301729,0.019448,0.000000,0.072,0.276310,St. Mary Parish,LA,Louisiana,True
108,22045,29.809222,-91.801563,POINT (-91.80156296 29.80922183),0.113679,0.054059,0.000000,0.062,0.200135,Iberia Parish,LA,Louisiana,True
110,22007,29.910402,-91.125931,POINT (-91.12593106 29.91040164),0.164233,0.002237,0.000000,0.066,0.293590,Assumption Parish,LA,Louisiana,True
117,22099,30.266729,-91.614339,POINT (-91.61433851 30.26672879),0.000000,0.195790,0.000000,0.074,0.256247,St. Martin Parish,LA,Louisiana,True
411,48189,33.911900,-101.628000,POINT (-101.628 33.9119),0.000000,0.000000,0.764574,0.092,0.052670,Hale County,TX,Texas,True
489,40039,35.743100,-98.672600,POINT (-98.6726 35.7431),0.000000,0.000000,0.867297,0.164,0.065250,Custer County,OK,Oklahoma,True
493,40011,35.809258,-98.423469,POINT (-98.42346929 35.80925801),0.883969,0.000000,0.000000,0.117,0.007230,Blaine County,OK,Oklahoma,True
496,40073,35.835815,-98.057775,POINT (-98.0577754 35.83581459),0.725726,0.000000,0.000000,0.057,0.000000,Kingfisher County,OK,Oklahoma,True
534,51810,36.886800,-75.491600,POINT (-75.4916 36.8868),0.000000,0.000000,1.000000,0.151,0.100000,Virginia Beach city,VA,Virginia,True
594,54017,39.286922,-80.715827,POINT (-80.7158273 39.28692158),0.833660,0.115187,0.000000,0.165,0.000000,Doddridge County,WV,West Virginia,True
623,54051,39.753475,-80.778286,POINT (-80.7782858 39.75347505),0.828035,0.272035,0.000000,0.139,0.000000,Marshall County,WV,West Virginia,True
647,54069,40.082236,-80.579376,POINT (-80.57937574 40.08223565),0.000000,0.329953,0.000000,0.085,0.000000,Ohio County,WV,West Virginia,True
650,39013,40.099918,-80.958314,POINT (-80.95831393 40.09991816),0.831903,0.000000,0.000000,0.094,0.000000,Belmont County,OH,Ohio,True
656,8123,40.198000,-104.731000,POINT (-104.731 40.198),0.000000,1.000000,0.000000,0.151,0.100000,Weld County,CO,Colorado,True
671,39067,40.378132,-81.076124,POINT (-81.07612397 40.37813221),0.000000,0.384197,0.000000,0.089,0.000000,Harrison County,OH,Ohio,True
678,17053,40.454400,-88.014800,POINT (-88.0148 40.4544),0.000000,0.000000,0.603835,0.004,0.000000,Ford County,IL,Illinois,True
679,18171,40.457800,-87.383000,POINT (-87.383 40.4578),0.000000,0.000000,0.739282,0.022,0.200000,Warren County,IN,Indiana,True
713,17105,40.968800,-88.380100,POINT (-88.3801 40.9688),0.000000,0.000000,0.699737,0.006,0.000000,Livingston County,IL,Illinois,True
745,19001,41.256800,-94.406100,POINT (-94.4061 41.2568),0.000000,0.000000,0.739421,0.028,0.366092,Adair County,IA,Iowa,True
785,42015,41.649466,-76.366726,POINT (-76.36672614 41.64946569),1.000000,0.000000,0.000000,0.165,0.000000,Bradford County,PA,Pennsylvania,True
857,31089,42.560700,-98.444300,POINT (-98.4443 42.5607),0.000000,0.000000,0.739770,0.120,0.000000,Holt County,NE,Nebraska,True
1166,38105,48.141206,-103.247655,POINT (-103.2476551 48.14120592),0.533694,0.000000,0.000000,0.046,0.000000,Williams County,ND,North Dakota,True